### ISSUE TITLE
Microsoft Defender warning latest build 

### ISSUE THREAD

**Issue by lordunix** [trholding/llama2.c#8]
Latest build raises Microsoft Defender warning with:

Trojan:Win32/Wacatac.B!ml

**Comment by trholding** [comment]
Thank you for bringing this to my attention. This is a known issue:

https://github.com/jart/cosmopolitan/issues/342

The warning happens only with cosmocc builds and it is a false positive.

Basically with cosmocc builds, the same binary works for all OSes, antivirus and virustotal misinterpret that as a signature of viruses.

This can go away only if we or upstream purchases expensive code signing certificates from microsoft. The warning is actually generated and put int AV databases by Microsoft, as part of Windows Smartscreen to discourage unsigned executables. 

You can use the tools mentioned in the thread to inspect and also if people want to see portable binaries from indie developers like us, then users could go to various Antivirus contact forms or even add Virus Total comments and mark ours as false positive.

On the other hand this is a open source project, you can audit each line of code and build non portable binaries or normal binaries yourself by cloning this project and following instructions.

However even the self compiled portable cosmocc binaries will fail the virus total check due to false positive. Normal binaries don't face that problem.

I'll add a note about this issue in the project description in the next commit.
